# Generated by Django 5.2 on 2025-04-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile", models.ImageField(upload_to="", verbose_name="프로필")),
                ("real_name", models.CharField(max_length=20, verbose_name="실명")),
                ("user_name", models.CharField(max_length=20, verbose_name="아이디")),
                ("bio", models.TextField(blank=True, verbose_name="자기소개")),
            ],
        ),
    ]
