# Generated by Django 5.2 on 2025-04-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="제목")),
                ("image", models.ImageField(upload_to="", verbose_name="이미지")),
                ("content", models.TextField(verbose_name="네용")),
                ("created_at", models.DateTimeField(verbose_name="작성일")),
                ("updated_at", models.DateTimeField(verbose_name="수정일")),
            ],
        ),
    ]
