# Generated by Django 5.2 on 2025-04-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="log",
            name="content",
            field=models.TextField(verbose_name="내용"),
        ),
    ]
