# Generated by Django 5.2 on 2025-04-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0002_remove_log_updated_at_alter_log_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="log",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="이미지"
            ),
        ),
    ]
